Fix output tests for location errors when running in async mode.
In this mode, an additional error was emitted, which made the test fail:
Error: There are pending proofs: Unnamed_thm.