Fixing a little location bug with recursive binders.
Note that localisation cannot be perfect anyways, as in the following
example, where there is no way to highlight in the original input a
syntactically stand-alone subterm where the error occurs.

> Check forall (y:nat) (x:=0), y.
>       ^^^^^^^^^^^^^^^^^^^^^^^^
Error: In environment
y : nat
The term "let x := 0 in y" has type "nat" which should be Set, Prop or Type.

(cherry picked from commit 4af1609cd70cca670109dfd6dfa06ed02034f7ae)