Improve coqpp error message for SELF in anonymous entry
Something like "("; [ s = SELF -> { s } ]; ")" in a GRAMMAR EXTEND in
a mlg file was causing an error message such as

OCAMLOPT  f.ml
File "f.mlg", line 179, characters 55-67:  # not in a semantic rule so line doesn't match anything in the mlg file
Error: This expression has type ('a, Extend.mayrec, 'a) Extend.symbol
       but an expression was expected of type
         ('a, Extend.norec, 'b) Extend.symbol
       Type Extend.mayrec is not compatible with type Extend.norec

It is now

COQPP   f.mlg
Error: 'SELF' or 'NEXT' illegal in anonymous entry level