Dune: remove -short-paths flag.
This makes it so that
~~~ocaml
module M = struct
  type a
  let f (x:a) = x
end

type b = M.a

let _ = M.f 2
~~~
We get

    Error: This expression has type int but an expression was expected of type M.a

instead of

    Error: This expression has type int but an expression was expected of type b

We want this for Coq since we have numerous aliases in this pattern,
eg module_ident = Id.t in names.

See https://github.com/ocaml/dune/issues/1794 https://caml.inria.fr/mantis/view.php?id=7911