Revert "Protect printing of intro-patterns from collision when "[|" or "|]"" because this commit triggers a
Error: Files proofs/proofs.cma(Miscprint)
       and /usr/local/lib/ocaml/compiler-libs/ocamlcommon.cma(Lexer)
       make inconsistent assumptions over interface Lexer

Adding two extra spaces systematically instead.

This reverts commit 72be1f6beafafc3edd30df673fbb6c7e88f8fac7.