Fix a minor bug in NonPar error
The system was referring to the position of a parameters including
let-definitions when it meant without them.

Example:
  Inductive I (f := fun x : nat => x)
              (h := fun x : nat => x) n
              (g := fun x : nat => x) : Type :=
  c : I (f 0).
raises :
Error: Last occurrence of "I" must have "f" as 1st argument in  "I (f
0)".
with "f" instead of "n".