explain_unification_error: reinfer universe inconsistencies
and missing constraints

Fix #17420

I'm a bit worried about perf for this.
The bench probably wouldn't tell us since this is about failures.