make sure that "ocamllibdep" properly recognizes Ocaml modules that are all upper-case
At the moment, when one tries to add an Ocaml module to Coq code-base
which is composed just from upper-cases letters,
the compilation fails with an error:

  File "......ml", line 1:
  Error: Error while linking ...
  Reference to undefined global `FOO'

This commit removes the restriction.