Remove Mltop.add_path as it is no longer possible to import files from subdirectories.
Using Mltop.add_path instead of Mltop.add_rec_path causes the following
kind of behavior:

$ coqtop -nois
Coq < Require Import Coq.Init.Datatypes.
Error: Cannot find a physical path bound to logical path Coq.Init.

The only case where its use is still warranted is the implicit "." path. It
shall not be recursive because Coq might be called from about anywhere.

This patch also removes -I-as since its behavior is no longer the one from
8.4 so it is not worth keeping it around.